import numpy as np
print("Familiarize with the functions to create an uninitialized array")
a1=np.empty(2,dtype=int,order='c')
print(a1)
print("array with all elements as 1")
a2=np.ones(4,dtype=int,order='c')
print(a2)
print("all elements as 0")
a3=np.zeros(4,dtype=int,order='c')
print(a3)